#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the first argument, like:
#
#           sh gradle
#
#       If you have 'bash', you can also run it like:
#
#           bash gradle
#
#       Or you can just run it directly in your current shell if it is compliant.
#
#   (2) This script attempts to find your Java installation and sets the JAVA_HOME
#       environment variable accordingly. If Java is not found, the build will fail.
#
#   (3) This script uses the Gradle wrapper JAR file. The wrapper JAR is a
#       single-file jar that contains all the necessary Gradle code to run a build.
#       In most cases, you do not need to download the wrapper JAR manually; it is
#       bundled with the wrapper script.
#
#   (4) The wrapper script is executed using 'sh' by default. If you are using a
#       different shell, you may need to change the shebang line.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available file descriptors if possible
if command -v ulimit >/dev/null 2>&1; then
    ulimit -n 4096 || true
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath 'gradle-launcher-*.jar'
#   * the jar file (which may be a symlink as well)
#   * and the JVM arguments

set -- \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these arguments contains shell metacharacters
# that should not be escaped, but that seems very unlikely.
#
# The idea is to make this script usable for any POSIX-compliant shell, even
# if it does not support arrays or command substitution.
#

# Save original IFS
IFS=$(printf '\n\t')

# If we have Windows path separators, replace them with POSIX ones.
# We can't use sed because we might be on a system where sed doesn't support the 's' flag.
case "$(uname -s)" in
    CYGWIN*|MINGW*|MSYS*)
        # Convert paths to POSIX style
        CLASSPATH=$(cygpath -w "$CLASSPATH" 2>/dev/null || echo "$CLASSPATH")
        JAVA_HOME=$(cygpath -w "$JAVA_HOME" 2>/dev/null || echo "$JAVA_HOME")
        ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! ulimit -n 4096 >/dev/null 2>&1; then
    echo "Note: ulimit -n 4096 failed." >&2
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath 'gradle-launcher-*.jar'
#   * the jar file (which may be a symlink as well)
#   * and the JVM arguments

# Find the jar file.
if [ -n "$APP_HOME" ] ; then
    JAR_FILE="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
    if [ ! -f "$JAR_FILE" ]; then
        echo "Could not find gradle wrapper jar: $JAR_FILE" >&2
        exit 1
    fi
else
    echo "APP_HOME is not set. Cannot find gradle wrapper jar." >&2
    exit 1
fi

# Run the wrapper.
exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    -jar "$JAR_FILE" \
    "$@"